export const arrayCategory = [
    "Todo"
    ,"Mate"
    ,"Mates de Madera" 
    ,"Mates de Acero"
    ,"Mates de Calabaza"
    ,"Yerbera y azucarera"
    ,"Bombillas de Acero"
    ,"Blister"
    ,"Botellas Plásticas"
    ,"Bombillas de Alpaca"
    ,"Bombillas de Acero"
    ,"Latas"
    ,"Set Materos" 
    ,"Acesorio"
    ,"Vaso Térmico"
]