--
-- PostgreSQL database dump
--

\restrict as07bVq7a9QT687dtXq9E3ylSmC9JyMXJ1CnAkGDDkyXPyNzJnU8snNNRBxn7O6

-- Dumped from database version 18.3 (Ubuntu 18.3-1.pgdg24.04+1)
-- Dumped by pg_dump version 18.3 (Ubuntu 18.3-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categorias; Type: TABLE; Schema: public; Owner: marcobenega
--

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nombre character varying(100)
);


ALTER TABLE public.categorias OWNER TO marcobenega;

--
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: marcobenega
--

CREATE SEQUENCE public.categorias_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.categorias_id_seq OWNER TO marcobenega;

--
-- Name: categorias_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marcobenega
--

ALTER SEQUENCE public.categorias_id_seq OWNED BY public.categorias.id;


--
-- Name: producto_categoria; Type: TABLE; Schema: public; Owner: marcobenega
--

CREATE TABLE public.producto_categoria (
    producto_id integer NOT NULL,
    categoria_id integer NOT NULL
);


ALTER TABLE public.producto_categoria OWNER TO marcobenega;

--
-- Name: productos; Type: TABLE; Schema: public; Owner: marcobenega
--

CREATE TABLE public.productos (
    id integer NOT NULL,
    codigo character varying(50),
    nombre text,
    precio_unitario numeric(10,2),
    cantidad integer,
    eliminado boolean,
    estado boolean,
    query_link text
);


ALTER TABLE public.productos OWNER TO marcobenega;

--
-- Name: productos_destacados; Type: TABLE; Schema: public; Owner: marcobenega
--

CREATE TABLE public.productos_destacados (
    id integer NOT NULL,
    producto_id integer NOT NULL
);


ALTER TABLE public.productos_destacados OWNER TO marcobenega;

--
-- Name: productos_destacados_id_seq; Type: SEQUENCE; Schema: public; Owner: marcobenega
--

CREATE SEQUENCE public.productos_destacados_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.productos_destacados_id_seq OWNER TO marcobenega;

--
-- Name: productos_destacados_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marcobenega
--

ALTER SEQUENCE public.productos_destacados_id_seq OWNED BY public.productos_destacados.id;


--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: marcobenega
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: marcobenega
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(50) DEFAULT 'admin'::character varying NOT NULL,
    estado boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.users OWNER TO marcobenega;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: marcobenega
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO marcobenega;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: marcobenega
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: categorias id; Type: DEFAULT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.categorias ALTER COLUMN id SET DEFAULT nextval('public.categorias_id_seq'::regclass);


--
-- Name: productos_destacados id; Type: DEFAULT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.productos_destacados ALTER COLUMN id SET DEFAULT nextval('public.productos_destacados_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: marcobenega
--

COPY public.categorias (id, nombre) FROM stdin;
23	Mate
24	Mates de Madera
25	Mates de Acero
26	Yerbera y azucarera
27	Bombillas de Acero
28	Blister
29	Canastas
30	Bolso Matero
31	Acesorio
32	Botellas Plásticas
33	Bombillas de Alpaca
34	Mates de Madera 
35	Mates de Calabaza
36	Latas
37	 Mates de Madera
38	 Mates de Madera 
39	Vaso Térmico
40	 Latas
41	Set Materos
42	Porta Termos
43	 Bombillas de Alpaca
44	Termos de Acero
\.


--
-- Data for Name: producto_categoria; Type: TABLE DATA; Schema: public; Owner: marcobenega
--

COPY public.producto_categoria (producto_id, categoria_id) FROM stdin;
0	23
0	24
1	24
1	25
10	26
11	26
12	26
13	26
14	26
15	27
16	27
17	27
17	28
18	29
18	30
19	31
2	31
20	31
21	31
22	32
23	32
24	33
25	33
26	33
27	33
28	33
28	34
29	34
3	34
30	34
31	34
32	34
32	35
33	35
34	35
35	35
36	36
37	36
38	36
39	36
4	36
4	37
40	37
40	38
41	38
42	38
43	38
44	38
45	38
46	39
47	39
47	40
47	41
48	41
49	42
5	42
50	42
51	42
52	42
53	42
54	42
55	42
56	42
57	42
57	43
58	43
59	43
6	43
60	43
61	43
62	44
63	44
64	44
65	44
66	44
67	44
68	44
69	44
7	44
70	44
71	44
72	44
73	44
74	44
75	44
76	44
77	44
78	44
8	44
9	44
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: marcobenega
--

COPY public.productos (id, codigo, nombre, precio_unitario, cantidad, eliminado, estado, query_link) FROM stdin;
0	480	Mate barrilito con guarda de acero algarrobo	8000.00	2	f	t	mate-barrilito-con-guarda-de-acero-algarrobo
1	5059	Mate Aero Acero	18000.00	2	f	t	mate-aero-acero
10	1013	Yerbera y azucarera flexible	11000.00	2	f	t	yerbera-y-azucarera-flexible
11	1703	Mate con tapa y bombilla	3200.00	1	f	f	mate-con-tapa-y-bombilla
12	1126	Mate viajero de plastico antivuelco	2600.00	1	f	f	mate-viajero-de-plastico-antivuelco
13	1403	Mate bravo negro	5800.00	1	f	t	mate-bravo-negro
14	2066	Mate meta 2.0	10000.00	2	f	t	mate-meta-2.0
15	1605	Bombilla acero inox gruesa con dije	2300.00	1	f	t	bombilla-acero-inox-gruesa-con-dije
16	1606	Bombilla acero inox gruesa chata en B	2050.00	0	f	f	bombilla-acero-inox-gruesa-chata-en-b
17	1607	Bombilla acero con estribo en blister	2700.00	3	f	t	bombilla-acero-con-estribo-en-blister
18	621	Canasto cuero premium	38000.00	1	f	t	porta-canasto-costura
19	1210	Tamizador con pico y vinilo Messi	4000.00	1	f	t	tamizador-con-pico-y-vinilo-messi
2	5089	Mate pary Acero	18000.00	0	f	t	mate-pary-acero
20	1206	Mate camionero 4 patas	15000.00	0	f	t	mate-camionero-4-patas
21	731	Set latas lisas pastel con mate de vidrio	3880.00	0	f	f	set-latas-lisas-pastel-con-mate-de-vidrio
22	1801	Botella 750cc con pico y banda silicon	3400.00	0	f	f	botella-750cc-con-pico-y-banda-silicon
23	1858	Mate termico orgon	9900.00	0	f	f	mate-termico-orgon
24	9979	Bombilla estribo y dije alpaca	6500.00	1	f	t	bombilla-estribo-y-dije-alpaca
25	3840	Bombilla extra curva tambor corta acero	5500.00	19	f	t	bombilla-extra-curva-tambor-corta-acero
26	1954	Mate goma eva vidrio pelota	5000.00	1	f	t	mate-goma-eva-vidrio-pelota
27	3101	Mate termico recto acero	5700.00	0	f	f	mate-termico-recto-acero
28	581	Mate algarrobo lustrado	3900.00	2	f	f	mate-algarrobo-lustrado
29	899	Bombilla alpaca pico loro	5050.00	3	f	t	bombilla-alpaca-pico-loro
3	919	Mate rombo sacayerba	3950.00	1	f	t	mate-rombo-sacayerba
30	4204	Mate camionero liso aluminio algarrobo negro	8500.00	0	f	f	mate-camionero-liso-aluminio-algarrobo-negro
31	2014	Mate ñandu aluminio algarrobo	14000.00	1	f	t	mate-ñandu-aluminio-algarrobo
32	2067	Mate imperial liso de acero calabaza	14000.00	0	f	f	mate-imperial-liso-de-acero-calabaza
33	481	Mate Perita con guarda de acero algarrobo	6400.00	1	f	f	mate-perita-con-guarda-de-acero-algarrobo
34	2716	Mate raíces con bombilla	10000.00	1	f	t	mate-raíces-con-bombilla
35	2132	Mate nativo con bombilla sacayerba marron	11000.00	3	f	t	mate-nativo-con-bombilla-sacayerba-marron
36	5122	Par de latas tambor	6500.00	3	f	t	par-de-latas-tambor
37	1608	Bombilla hexagonal en blister	2500.00	1	f	t	bombilla-hexagonal-en-blister
38	LUZMa	Luz matera	3500.00	6	f	t	luz-matera
39	809	bombilla acero fina baño alpaca	4000.00	0	f	f	bombilla-acero-fina-baño-alpaca
4	5053	Mate Hornero cincelado acero algarrobo	21000.00	0	f	t	mate-hornero-cincelado-acero-algarrobo
40	422	Mate cortado algarrobo	6600.00	2	f	t	mate-cortado-algarrobo
41	4118	Mate torpedo liso aluminio calabaza Negro	15000.00	2	f	t	mate-torpedo-liso-aluminio-calabaza-negro
42	425	Mate palo santo	5300.00	1	f	t	mate-palo-santo
43	3119	Mate pulido acero	7000.00	1	f	t	mate-pulido-acero
44	2621	Mate imperial vegano calabaza chico negro	9000.00	1	f	t	mate-imperial-vegano-calabaza-chico-negro
45	7401	Bombilla microfono acero	5000.00	3	f	t	bombilla-microfono-acero
46	1637	Vaso pintado aluminio 1 litro	6000.00	1	f	t	vaso-pintado-aluminio-1-litro
47	4012	Set matero	12000.00	2	f	t	set-matero
48	1992	Botella deportiva 750ml 	3000.00	4	f	f	botella-deportiva-750ml-
49	245	Bolso matero Urban	25000.00	1	f	t	bolso-matero-urban
5	2183	mate Hornero raya liso acero algarrobo	18000.00	0	f	f	mate-hornero-raya-liso-acero-algarrobo
50	254	Bolso matero con tapa	20000.00	1	f	t	bolso-matero-con-tapa
51	6813	Botella hidratacion tapa click AFA	7300.00	1	f	f	botella-hidratacion-tapa-click-afa
52	1839	Set anastasia	4750.00	0	f	f	set-anastasia
53	1779	Set de latas lisas color pastel sin mate	3880.00	2	f	f	set-de-latas-lisas-color-pastel-sin-mate
54	966	Mate calabaza Uruguayo floreado	8800.00	0	f	f	mate-calabaza-uruguayo-floreado
55	947	Mate animate glitter	2700.00	1	f	f	mate-animate-glitter
56	184	Mate porito alpaca con pie	7480.00	0	f	f	mate-porito-alpaca-con-pie
57	913	Limpia bombilla	400.00	3	f	t	limpia-bombilla
58	10113	Set de Latas tambor Marwal 	7200.00	2	f	t	set-de-latas-tambor-marwal-
59	8262	Vaso termico waterdog 450ml acero inox	34000.00	0	f	t	vaso-termico-waterdog-450ml-acero-inox
6	5623	Mate camionero vegano calabaza	8000.00	1	f	t	mate-camionero-vegano-calabaza
60	1042	kit tereré termo vaso y bombilla	14000.00	1	f	f	kit-tereré-termo-vaso-y-bombilla
61	4001	Mate imperial calabaza alpaca liso	27000.00	2	f	t	mate-imperial-calabaza-alpaca-liso
62	6411	Termo Acero WaterDog ombu1000 1L	60000.00	1	f	t	termo-acero-waterdog-ombu1000-1l
63	5025	Par de latas pintadas	6500.00	2	f	t	par-de-latas-pintadas
64	9003	Porta mate cuero 	16000.00	1	f	t	porta-mate-cuerina
65	5068	Mate Mola Acero con Bombilla	19500.00	2	f	t	mate-mola-acero-con-bombilla
66	2248	Mate imperial liso acero cuero croco calabaza	24300.00	1	f	t	mate-imperial-liso-acero-cuero-croco-calabaza
67	20280	Mate imperial liso cincelado acero calabaza	22500.00	1	f	t	mate-imperial-liso-cincelado-acero-calabaza
68	4973	Mate Oval acero	8500.00	2	f	t	mate-oval-acero
69	3106	Mate termico acero Copita	9000.00	1	f	t	mate-termico-acero-copita
7	512	Mate lustrado grabado	4000.00	2	f	t	mate-lustrado-grabado
70	2216	Mate camionero calabaza liso aluminio 	15500.00	1	f	f	mate-camionero-calabaza-liso-aluminio-
71	40120	Mate imperial cincelado Alpaca Calabaza	27000.00	1	f	t	mate-imperial-cincelado-alpaca-calabaza
72	2251	Mate imporial cincelado Base alpaca calabaza	28000.00	1	f	f	mate-imporial-cincelado-base-alpaca-calabaza
73	5050	Mate Hornero liso alpaca algarrobo	25000.00	1	f	t	mate-hornero-liso-alpaca-algarrobo
74	5101	Mate jujeño liso acero	20000.00	1	f	t	mate-jujeño-liso-acero
75	4106	Mate calabaza alpaca 	15000.00	1	f	t	mate-calabaza-alpaca-
76	819	Mate calabaza alpaca con virola fina	15000.00	1	f	t	mate-calabaza-alpaca-con-virola-fina
77	2013	Vaso Termico Huron 2.0 473ml CONTIGO	30000.00	1	f	t	vaso-termico-huron-2.0-473ml-contigo
78	3400	Media Canasta Ovalada de Cuero Premium 	30200.00	1	f	t	media-canasta-ovalada-de-cuero-premium
8	696	Mate calabaza con virola	2500.00	1	f	f	mate-calabaza-con-virola
9	2028	Mate cuyo orgon	6300.00	1	f	f	mate-cuyo-orgon
\.


--
-- Data for Name: productos_destacados; Type: TABLE DATA; Schema: public; Owner: marcobenega
--

COPY public.productos_destacados (id, producto_id) FROM stdin;
1	0
2	18
3	77
4	59
5	64
6	38
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: marcobenega
--

COPY public.users (id, email, password, role, estado, created_at) FROM stdin;
1	marcobenega@gmail.com	$argon2id$v=19$m=65536,t=3,p=4$Gsk88GgYnanASkhgEMipuQ$nzdRTscbS0ZLo0wRye9JqtyvrIsz8Bq7SKHUmuXeGj8	admin	t	2026-03-12 01:32:11.493623
\.


--
-- Name: categorias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcobenega
--

SELECT pg_catalog.setval('public.categorias_id_seq', 44, true);


--
-- Name: productos_destacados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcobenega
--

SELECT pg_catalog.setval('public.productos_destacados_id_seq', 6, true);


--
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcobenega
--

SELECT pg_catalog.setval('public.productos_id_seq', 79, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcobenega
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: categorias categorias_nombre_key; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_nombre_key UNIQUE (nombre);


--
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- Name: producto_categoria producto_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.producto_categoria
    ADD CONSTRAINT producto_categoria_pkey PRIMARY KEY (producto_id, categoria_id);


--
-- Name: productos_destacados productos_destacados_pkey; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.productos_destacados
    ADD CONSTRAINT productos_destacados_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: productos_destacados unique_producto_destacado; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.productos_destacados
    ADD CONSTRAINT unique_producto_destacado UNIQUE (producto_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: productos_destacados fk_producto; Type: FK CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.productos_destacados
    ADD CONSTRAINT fk_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- Name: producto_categoria producto_categoria_categoria_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.producto_categoria
    ADD CONSTRAINT producto_categoria_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);


--
-- Name: producto_categoria producto_categoria_producto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: marcobenega
--

ALTER TABLE ONLY public.producto_categoria
    ADD CONSTRAINT producto_categoria_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id);


--
-- PostgreSQL database dump complete
--

\unrestrict as07bVq7a9QT687dtXq9E3ylSmC9JyMXJ1CnAkGDDkyXPyNzJnU8snNNRBxn7O6

