import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import styles from "../resources/styles/pageMain.module.css";
import Sidebar from "./component/SideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.container}>
            <Sidebar/>

          <div className={styles.cont}>
            <header className={styles.head}>
            <h1 className={styles.title}>Nuestro catalogo</h1>
            </header>
            
            <nav className={styles.navBar}>
              <p>ejmolo 1</p>
              <p>ejemplo 1</p>
            </nav>

            {children}

          </div>
        
      </div>
        
      <footer >

  
</footer>
      </body>
    </html>
  );
}
